name: RedOchsenbein
favicon: null
layout_spectrum: 0
typography_spectrum: 0.42226
title: 'Composer for commercials, games and TV'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01040d'
    - '#3f4948'
    - '#ede2d2'
    - '#afa390'
    - '#a14536'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
