name: RedOchsenbein
favicon: null
layout_spectrum: 0.3583446030970663
typography_spectrum: 0.9906619603279978
title: 'Composer for commercials, games and TV'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01040d'
    - '#3f4948'
    - '#ede2d2'
    - '#afa390'
    - '#a14536'
  brandStrength: 0.375
  lightness: 0.40242877905257046
  saturation: 1
  rhythmicContrast: 0.6262019546702504
purpose: []
